# IntelliJ Platform Artifacts Repositories
pluginGroup = com.pocketfm.ktlintv2
pluginName = ktlintv2
pluginVersion = 1.0.0

# IntelliJ Platform version
platformType = IC
platformVersion = 2024.1

# Kotlin version
kotlinVersion = 2.0.21

# Gradle IntelliJ Plugin version
gradleIntellijPluginVersion = 1.17.2

# Java version
javaVersion = 17

# Target IDEs
sinceBuild = 241
untilBuild = 243.*
